---
title: "Circos_Analysis"
author: "Kfir Inbal"
date: "2024-01-21"
output: html_document
---

```{r}
#NOTE: In this experiments CD11 == cDC cells (cells that express CD11)
setwd("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code")
library(circlize)
library(viridis)
library(ComplexHeatmap)
library(knitr)
library(tidyverse)
library(stringr)
library(reshape2)
library(pheatmap)
library(dendsort)
library(RColorBrewer)
library(grid)
library(igraph)
library(readxl)
library(conflicted)
library("org.Mm.eg.db")
library("annotate")
library(DESeq2)
```

```{r Helper data, echo=FALSE}
#HelperDataPath <- "E:/data/LR_Interaction_Algorithm/"
#HelperDataPath <- "D:/user/Desktop/Shai/LR_Interaction_Algorithm/"
HelperDataPath <- "C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\LR_Interaction_Algorithm"

LigandReceptorTable <- read.delim(paste0(HelperDataPath,"\\LigandReceptorTableMouse.tsv"),
                                  sep = "\t", header = T,  quote="\"" , check.names=FALSE)  
#DSA related data
ProtNamesInfo <- read.delim(paste0(HelperDataPath,"\\Mouse.protein.info.v11.0.txt"),
                            sep = "\t", header = T, quote = "", colClasses = c("character" ,"character" ,"numeric"))
ENSNamesInfo <- ProtNamesInfo
rownames(ENSNamesInfo) <- ENSNamesInfo$protein_external_id
ENSNamesInfo <- ENSNamesInfo %>% dplyr::select(-c(protein_external_id))
ProtActions <- read.delim(paste0(HelperDataPath,"\\Mouse.protein.actions.v11.0.txt"),
                           sep = "\t", header = T, quote = "")

source(paste0(HelperDataPath,'\\LR_interaction_functions\\LR_Func.R'))
source(paste0(HelperDataPath,'\\LR_interaction_functions\\CreateCircosPlot_Func.R'))
source(paste0(HelperDataPath,'\\LR_interaction_functions\\LegendNcolor_Funcs.R'))
source(paste0(HelperDataPath,'\\LR_interaction_functions\\Parsing_Funcs.R'))

```



```{r}
#Ligands-receptors lists load
Ligand_Recep_Mouse <- read.table(file = '.\\Gene_lists\\LigandReceptorTableMouse.tsv', sep = '\t', header = TRUE)

#Subsetting to only ligands
ligands_subset <- unique(Ligand_Recep_Mouse[, which(colnames(Ligand_Recep_Mouse) == "from")])
#write.table(ligands_subset, ".\\ligands_subset.txt", row.names = FALSE, col.names = FALSE)
#Subsetting to only receptors
receptors_subset <- unique(Ligand_Recep_Mouse[,which(colnames(Ligand_Recep_Mouse) == "to")])
#write.table(receptors_subset, ".\\receptors_subset.txt", row.names = FALSE, col.names = FALSE)


```

```{r}
##Protein-Protein interactions in mouse
directed_mouse_ppi <- read.table("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\LR_Interaction_Algorithm\\mippie_ppi_v1_0.tsv", sep = "\t", header = T)

directed_mouse_ppi <- directed_mouse_ppi %>% dplyr::select(c(entrezA, entrezB, MIPPIE_score))
colnames(directed_mouse_ppi) <- c("Input-node GeneID", "Output-node GeneID", "Edge direction score")
directed_mouse_ppi$'Input-node Gene Symbol' <- getSYMBOL(c(as.character(as.matrix(directed_mouse_ppi$`Input-node GeneID`))), data = "org.Mm.eg")

directed_mouse_ppi$'Output-node Gene Symbol' <- getSYMBOL(c(as.character(as.matrix(directed_mouse_ppi$`Output-node GeneID`))), data = "org.Mm.eg")
directed_mouse_ppi <- directed_mouse_ppi %>% relocate('Input-node Gene Symbol', .before = "Input-node GeneID")
directed_mouse_ppi <- directed_mouse_ppi %>% relocate('Output-node Gene Symbol', .before = "Output-node GeneID")

write.csv(directed_mouse_ppi, "C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\directed_mouse_ppi.csv")

```

```{r}
#LIGANDS DEGenes
###############################################################################################
### MoDC 6H up regulated Ligands in both DEGs of MoDC_6H_vs_cDC_6H and MoDC_6H_vs_Naive 

#MoDC_6H_vs_cDC_6H <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\MoDC_CD11c\\DEG_MoDC_CD11c_--MoDC_Treatment_6H_Versus_cDC_Treatment_6H--_padj_lt_0.05.csv", row.names = 1)

MoDC_6H_vs_cDC_6H <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\MoDC_CD11c\\Without_Wash\\DEG_MoDC_CD11c_NoWash_--MoDC_Treatment_6H_Versus_cDC_Treatment_6H--_padj_lt_0.05.csv", row.names = 1)

MoDC_6H_vs_cDC_6H_up <- subset(MoDC_6H_vs_cDC_6H, lgFC_MoDC_Treatment_6H_vs_cDC_Treatment_6H > 0)

#MoDC_6H_vs_Naive <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\MoDC\\With_Wash\\Without_Naive_MoDC_M4_Sample\\DEGs\\DEG_InVitro_MoDC_Without_Naive_M4_--Treatment_6H_Versus_Naive--_padj_lt_0.05.csv", row.names = 1)

MoDC_6H_vs_Naive <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\MoDC\\Without_Wash\\Without_Naive_MoDC_M4_Sample\\DEG_InVitro_MoDC_6HvsMoDC_Naive_Without_Naive_M4_--Treatment_6H_Versus_Naive--_padj_lt_0.05.csv", row.names = 1)

MoDC_6H_vs_Naive_up <- subset(MoDC_6H_vs_Naive, lgFC_Treatment_6H_vs_Naive > 0)

MoDC6H_Intersected_up <- merge(MoDC_6H_vs_cDC_6H_up,MoDC_6H_vs_Naive_up, by = "row.names")

#First column to row.names
MoDC6H_Intersected_up <- MoDC6H_Intersected_up %>% remove_rownames %>% column_to_rownames(var="Row.names")

MoDC6H_Intersected_up_Ligands <- subset(MoDC6H_Intersected_up, row.names(MoDC6H_Intersected_up) %in% ligands_subset)

#Selecting lgFC_MoDC_Treatment_6H_vs_CD11c_Treatment_6H column (no special reason) and padj.x
MoDC6H_Intersected_up_Ligands <- dplyr::select(MoDC6H_Intersected_up_Ligands, lgFC_MoDC_Treatment_6H_vs_cDC_Treatment_6H,padj.x)

colnames(MoDC6H_Intersected_up_Ligands) <- c("log2FoldChange","padj")

MoDC6H_Intersected_up_Ligands <- tibble::rownames_to_column(MoDC6H_Intersected_up_Ligands, "gene_name")

write.csv(MoDC6H_Intersected_up_Ligands, ".\\Circos_Code\\MoDC6H_Intersected_up_Ligands.csv")

###############################################################################################
### cDC 6H up regulated ligands vs cDC Naive 

cDC_6H_VS_cDC_Naive <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\CD11c\\DEG_cDC_6H_VS_cDC_Naive_--Treatment_6H_Versus_Naive--_padj_lt_0.05.csv", row.names = 1)

cDC_6H_VS_cDC_Naive_up <- subset(cDC_6H_VS_cDC_Naive, lgFC_Treatment_6H_vs_Naive > 0)

cDC_6H_VS_cDC_Naive_up_Ligands <- subset(cDC_6H_VS_cDC_Naive_up, row.names(cDC_6H_VS_cDC_Naive_up) %in% ligands_subset)

cDC_6H_VS_cDC_Naive_up_Ligands <- dplyr::select(cDC_6H_VS_cDC_Naive_up_Ligands, lgFC_Treatment_6H_vs_Naive,padj)

colnames(cDC_6H_VS_cDC_Naive_up_Ligands) <- c("log2FoldChange","padj")

cDC_6H_VS_cDC_Naive_up_Ligands <- tibble::rownames_to_column(cDC_6H_VS_cDC_Naive_up_Ligands, "gene_name")


write.csv(cDC_6H_VS_cDC_Naive_up_Ligands, ".\\Circos_Code\\cDC_6H_VS_cDC_Naive_up_Ligands.csv")

###############################################################################################
###  In vivo MoDC Tumor up regulated ligands vs MoDC DLN 

MoDC_Tumor_VS_MoDC_DLN <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Tomer_Data\\moDC\\Results\\DEGenes\\DEG_moDC_LN_Tumor_In_Vivo_--moDC_Tumor_Versus_moDC_LN--_padj_lt_0.05.csv", row.names = 1)

MoDC_Tumor_VS_MoDC_DLN_up <- subset(MoDC_Tumor_VS_MoDC_DLN, lgFC_moDC_Tumor_vs_moDC_LN > 0)

MoDC_Tumor_VS_MoDC_DLN_up_Ligands <- subset(MoDC_Tumor_VS_MoDC_DLN_up, row.names(MoDC_Tumor_VS_MoDC_DLN_up) %in% ligands_subset)

MoDC_Tumor_VS_MoDC_DLN_up_Ligands <- dplyr::select(MoDC_Tumor_VS_MoDC_DLN_up_Ligands, lgFC_moDC_Tumor_vs_moDC_LN,padj)

colnames(MoDC_Tumor_VS_MoDC_DLN_up_Ligands) <- c("log2FoldChange","padj")

MoDC_Tumor_VS_MoDC_DLN_up_Ligands <- tibble::rownames_to_column(MoDC_Tumor_VS_MoDC_DLN_up_Ligands, "gene_name")


write.csv(MoDC_Tumor_VS_MoDC_DLN_up_Ligands, ".\\Circos_Code\\MoDC_Tumor_VS_MoDC_DLN_up_Ligands.csv")



###############################################################################################
###  In vivo MoDC Tumor up regulated vs MoDC DLN intersected with In vitro MoDC_6H_unique up ligands

MoDC_Tumor_VS_MoDC_DLN <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Tomer_Data\\moDC\\Results\\DEGenes\\DEG_moDC_LN_Tumor_In_Vivo_--moDC_Tumor_Versus_moDC_LN--_padj_lt_0.05.csv", row.names = 1)

MoDC_Tumor_VS_MoDC_DLN_up <- subset(MoDC_Tumor_VS_MoDC_DLN, lgFC_moDC_Tumor_vs_moDC_LN > 0)

MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands <- subset(MoDC_Tumor_VS_MoDC_DLN_up, row.names(MoDC_Tumor_VS_MoDC_DLN_up) %in% MoDC6H_Intersected_up_Ligands$gene_name)

MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands <- dplyr::select(MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands, lgFC_moDC_Tumor_vs_moDC_LN,padj)

colnames(MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands) <- c("log2FoldChange","padj")

MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands <- tibble::rownames_to_column(MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands, "gene_name")


write.csv(MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands, ".\\Circos_Code\\MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands.csv")

```

```{r}
#RECEPTORS DEGenes

###############################################################################################
### T cells PCD11_LMoDC up regulated receptors vs PMoDC 

T_Cells_LMoDC_vs_PMoDC <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\T_Cells\\Priming_Licensing_Only\\DEG_T_Cells_Treatments_Only_--LMoDC_Versus_PMoDC--_padj_lt_0.05.csv", row.names = 1)


T_Cells_LMoDC_vs_PMoDC_up <- subset(T_Cells_LMoDC_vs_PMoDC, lgFC_LMoDC_vs_PMoDC > 0)


T_Cells_LMoDC_vs_PMoDC_up_Receptors <- subset(T_Cells_LMoDC_vs_PMoDC_up, row.names(T_Cells_LMoDC_vs_PMoDC_up) %in% receptors_subset)

T_Cells_LMoDC_vs_PMoDC_up_Receptors <- dplyr::select(T_Cells_LMoDC_vs_PMoDC_up_Receptors, lgFC_LMoDC_vs_PMoDC,padj)

colnames(T_Cells_LMoDC_vs_PMoDC_up_Receptors) <- c("log2FoldChange","padj")

T_Cells_LMoDC_vs_PMoDC_up_Receptors <- tibble::rownames_to_column(T_Cells_LMoDC_vs_PMoDC_up_Receptors, "gene_name")


write.csv(T_Cells_LMoDC_vs_PMoDC_up_Receptors, ".\\Circos_Code\\T_Cells_LMoDC_vs_PMoDC_up_Receptors.csv")



###############################################################################################
### T cells PCD11_LMoDC up regulated receptors vs PcDC 

T_Cells_LMoDC_vs_PcDC <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\T_Cells\\Priming_Licensing_Only\\DEG_T_Cells_Treatments_Only_--LMoDC_Versus_PcDC--_padj_lt_0.05.csv", row.names = 1)


T_Cells_LMoDC_vs_PcDC_up <- subset(T_Cells_LMoDC_vs_PcDC, lgFC_LMoDC_vs_PcDC > 0)


T_Cells_LMoDC_vs_PcDC_up_Receptors <- subset(T_Cells_LMoDC_vs_PcDC_up, row.names(T_Cells_LMoDC_vs_PcDC_up) %in% receptors_subset)

T_Cells_LMoDC_vs_PcDC_up_Receptors <- dplyr::select(T_Cells_LMoDC_vs_PcDC_up_Receptors, lgFC_LMoDC_vs_PcDC,padj)

colnames(T_Cells_LMoDC_vs_PcDC_up_Receptors) <- c("log2FoldChange","padj")

T_Cells_LMoDC_vs_PcDC_up_Receptors <- tibble::rownames_to_column(T_Cells_LMoDC_vs_PcDC_up_Receptors, "gene_name")


write.csv(T_Cells_LMoDC_vs_PcDC_up_Receptors, ".\\Circos_Code\\T_Cells_LMoDC_vs_PcDC_up_Receptors.csv")




###############################################################################################
### T cells PCD11_LCD11 up regulated receptors vs PCD11

T_Cells_LCD11_vs_PCD11 <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\T_Cells\\Priming_Licensing_Only\\DEG_T_Cells_Treatments_Only_--LcDC_Versus_PcDC--_padj_lt_0.05.csv", row.names = 1)


T_Cells_LCD11_vs_PCD11_up <- subset(T_Cells_LCD11_vs_PCD11, lgFC_LcDC_vs_PcDC > 0)


T_Cells_LCD11_vs_PCD11_up_Receptors <- subset(T_Cells_LCD11_vs_PCD11_up, row.names(T_Cells_LCD11_vs_PCD11_up) %in% receptors_subset)

T_Cells_LCD11_vs_PCD11_up_Receptors <- dplyr::select(T_Cells_LCD11_vs_PCD11_up_Receptors, lgFC_LcDC_vs_PcDC,padj)

colnames(T_Cells_LCD11_vs_PCD11_up_Receptors) <- c("log2FoldChange","padj")

T_Cells_LCD11_vs_PCD11_up_Receptors <- tibble::rownames_to_column(T_Cells_LCD11_vs_PCD11_up_Receptors, "gene_name")


write.csv(T_Cells_LCD11_vs_PCD11_up_Receptors, ".\\Circos_Code\\T_Cells_LCD11_vs_PCD11_up_Receptors.csv")

###############################################################################################
### In vivo T cells Tumor up regulated receptors vs T cells DLN

In_vivo_T_cells_Tumor_vs_DLN <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Tomer_Data\\T_Cells\\Results\\DEG_CD8_Tumor_DLN_In_Vivo_--CD8_Tumor_Versus_CD8_DLN--_padj_lt_0.05.csv", row.names = 1)


In_vivo_T_cells_Tumor_vs_DLN_up <- subset(In_vivo_T_cells_Tumor_vs_DLN, lgFC_CD8_Tumor_vs_CD8_DLN > 0)


In_vivo_T_cells_Tumor_vs_DLN_up_Receptors <- subset(In_vivo_T_cells_Tumor_vs_DLN_up, row.names(In_vivo_T_cells_Tumor_vs_DLN_up) %in% receptors_subset)

In_vivo_T_cells_Tumor_vs_DLN_up_Receptors <- dplyr::select(In_vivo_T_cells_Tumor_vs_DLN_up_Receptors, lgFC_CD8_Tumor_vs_CD8_DLN,padj)

colnames(In_vivo_T_cells_Tumor_vs_DLN_up_Receptors) <- c("log2FoldChange","padj")

In_vivo_T_cells_Tumor_vs_DLN_up_Receptors <- tibble::rownames_to_column(In_vivo_T_cells_Tumor_vs_DLN_up_Receptors, "gene_name")


write.csv(In_vivo_T_cells_Tumor_vs_DLN_up_Receptors, ".\\Circos_Code\\In_vivo_T_cells_Tumor_vs_DLN_up_Receptors.csv")



###############################################################################################
### In vivo T cells Tumor up regulated vs T cells DLN intersected with 

In_vivo_T_cells_Tumor_vs_DLN <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Tomer_Data\\T_Cells\\Results\\DEG_CD8_Tumor_DLN_In_Vivo_--CD8_Tumor_Versus_CD8_DLN--_padj_lt_0.05.csv", row.names = 1)


In_vivo_T_cells_Tumor_vs_DLN_up <- subset(In_vivo_T_cells_Tumor_vs_DLN, lgFC_CD8_Tumor_vs_CD8_DLN > 0)


In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors <- subset(In_vivo_T_cells_Tumor_vs_DLN_up, row.names(In_vivo_T_cells_Tumor_vs_DLN_up) %in% T_Cells_LMoDC_vs_PcDC_up_Receptors$gene_name)

In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors <- dplyr::select(In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors, lgFC_CD8_Tumor_vs_CD8_DLN,padj)

colnames(In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors) <- c("log2FoldChange","padj")

In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors <- tibble::rownames_to_column(In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors, "gene_name")


write.csv(In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors, ".\\Circos_Code\\In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors.csv")




###############################################################################################
### T cells PCD11_LMoDC up regulated receptors vs T cells PCD11_LcDC 

T_Cells_LMoDC_vs_LcDC <- read.csv("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\T_Cells\\Priming_Licensing_Only\\DEG_T_Cells_Treatments_Only_--LMoDC_Versus_LcDC--_padj_lt_0.05.csv", row.names = 1)


T_Cells_LMoDC_vs_LcDC_up <- subset(T_Cells_LMoDC_vs_LcDC, lgFC_LMoDC_vs_LcDC > 0)


T_Cells_LMoDC_vs_LcDC_up_Receptors <- subset(T_Cells_LMoDC_vs_LcDC_up, row.names(T_Cells_LMoDC_vs_LcDC_up) %in% receptors_subset)

T_Cells_LMoDC_vs_LcDC_up_Receptors <- dplyr::select(T_Cells_LMoDC_vs_LcDC_up_Receptors, lgFC_LMoDC_vs_LcDC,padj)

colnames(T_Cells_LMoDC_vs_LcDC_up_Receptors) <- c("log2FoldChange","padj")

T_Cells_LMoDC_vs_LcDC_up_Receptors <- tibble::rownames_to_column(T_Cells_LMoDC_vs_LcDC_up_Receptors, "gene_name")


write.csv(T_Cells_LMoDC_vs_LcDC_up_Receptors, ".\\Circos_Code\\T_Cells_LMoDC_vs_LcDC_up_Receptors.csv")


```


```{r}
#DESeq Analysis lists of the experiments loading:
MoDC_List <- readRDS("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\MoDC\\With_Wash\\Without_Naive_MoDC_M4_Sample\\InVitro_MoDC_Without_Naive_M4.rds")
T_Cells_Treatments_List <- readRDS("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\T_Cells\\Priming_Licensing_Only\\T_Cells_Treatments_Only.rds")
cDC_List <- readRDS("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\CD11c\\cDC_6H_VS_cDC_Naive.rds")
T_Cells_In_Vivo_List <- readRDS("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Tomer_Data\\T_Cells\\Results\\CD8_DLN_Tumor_In_Vivo.rds")
MoDC_In_vivo_List <- readRDS("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Tomer_Data\\moDC\\Results\\moDC_LN_Tumor_In_Vivo.rds")
```

```{r}
#Getting counts out of the lists:

MoDC_Counts <- as.data.frame(assay(MoDC_List$Counts_Normalized_data$data))
MoDC_Counts <- MoDC_Counts %>% dplyr::select(c("MoDC_6H_M1", "MoDC_6H_M2", "MoDC_6H_M3", "MoDC_6H_M4"))

cDC_Counts <- as.data.frame(assay(cDC_List$Counts_Normalized_data$data))
cDC_Counts <- cDC_Counts %>% dplyr::select(c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4"))

T_Treatments_Counts <- as.data.frame(assay(T_Cells_Treatments_List$Counts_Normalized_data$data))

T_Treatments_Counts_LMoDC <- T_Treatments_Counts %>% dplyr::select(c("T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4"))

T_Treatments_Counts_LcDC <- T_Treatments_Counts %>% dplyr::select(c("T_PCD11_LCD11_1", "T_PCD11_LCD11_2", "T_PCD11_LCD11_3", "T_PCD11_LCD11_4"))

T_Treatments_Counts_LMoDC_PcDC <- T_Treatments_Counts %>% dplyr::select(c("T_PimedCD11c_1","T_PimedCD11c_2","T_PimedCD11c_3","T_PimedCD11c_4","T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4")) #For sanity check of MoDC_6H/Naive+cDC_6H VS T_PcDC_LMoDC/T_PcDC

T_Cells_In_Vivo_Counts <- as.data.frame(assay(T_Cells_In_Vivo_List$Counts_Normalized_data$data))
T_Cells_In_Vivo_Counts_Tumor <- T_Cells_In_Vivo_Counts %>% dplyr::select(c("CD8_Tumor_1","CD8_Tumor_2","CD8_Tumor_3"))

MoDC_In_Vivo_Counts <- as.data.frame(assay(MoDC_In_vivo_List$Counts_Normalized_data$data))
MoDC_In_Vivo_Counts_Tumor <- MoDC_In_Vivo_Counts %>% dplyr::select(c("DC_Tumor1","DC_Tumor2","DC_Tumor3"))


```

```{r}
########################MoDC_6H/Naive+cDC_6H VS T_PcDC_LMoDC/T_PMoDC #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(MoDC_Counts, T_Treatments_Counts_LMoDC, by = "row.names")
names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'
RNAseqEXPMean$MoDC_6H <- rowMeans(RNAseqEXPMean[,c("MoDC_6H_M1", "MoDC_6H_M2", "MoDC_6H_M3", "MoDC_6H_M4") ])
RNAseqEXPMean$T_PCD11_LMoDC <- rowMeans(RNAseqEXPMean[,c("T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("MoDC_6H_M1", "MoDC_6H_M2", "MoDC_6H_M3", "MoDC_6H_M4","T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4"))

#Circos 
cell_pairs <- c(c("MoDC_6H","T_PCD11_LMoDC"))

LR <- createLRtable(fromCol = ReceptorParser(MoDC6H_Intersected_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(T_Cells_LMoDC_vs_PMoDC_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(T_Cells_LMoDC_vs_PMoDC_up_Receptors, cell_pairs[2], FC_thresh = 0), # Receptors
                   fromCol = ReceptorParser(MoDC6H_Intersected_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-Naive_",cell_pairs[2],"-PMoDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "MoDC_6H/Naive+cDC_6H unique up regulated Ligands VS T_PcDC_LMoDC/T_PMoDC up regulated Receptors")


```

```{r}
########################MoDC_6H/Naive+cDC_6H VS T_PcDC_LMoDC/T_PcDC_LcDC #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(MoDC_Counts, T_Treatments_Counts_LMoDC, by = "row.names")
names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'
RNAseqEXPMean$MoDC_6H <- rowMeans(RNAseqEXPMean[,c("MoDC_6H_M1", "MoDC_6H_M2", "MoDC_6H_M3", "MoDC_6H_M4") ])
RNAseqEXPMean$T_PCD11_LMoDC <- rowMeans(RNAseqEXPMean[,c("T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("MoDC_6H_M1", "MoDC_6H_M2", "MoDC_6H_M3", "MoDC_6H_M4","T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4"))

#Circos 
cell_pairs <- c(c("MoDC_6H","T_PCD11_LMoDC"))

LR <- createLRtable(fromCol = ReceptorParser(MoDC6H_Intersected_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(T_Cells_LMoDC_vs_LcDC_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(T_Cells_LMoDC_vs_LcDC_up_Receptors, cell_pairs[2], FC_thresh = 0), # Receptors
                   fromCol = ReceptorParser(MoDC6H_Intersected_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-Naive_",cell_pairs[2],"-PcDC_LcDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "MoDC_6H/Naive+cDC_6H unique up regulated Ligands VS T_PcDC_LMoDC/T_PcDC_LcDC up regulated Receptors")


```






```{r}
########################cDC_6H/Naive VS T_PcDC_LcDC/T_PcDC #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(cDC_Counts, T_Treatments_Counts_LcDC, by = "row.names")

names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'

RNAseqEXPMean$cDC_6H <- rowMeans(RNAseqEXPMean[,c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4")])
RNAseqEXPMean$T_PCD11_LCD11 <- rowMeans(RNAseqEXPMean[,c("T_PCD11_LCD11_1", "T_PCD11_LCD11_2", "T_PCD11_LCD11_3", "T_PCD11_LCD11_4") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4","T_PCD11_LCD11_1", "T_PCD11_LCD11_2", "T_PCD11_LCD11_3", "T_PCD11_LCD11_4"))

cell_pairs <- c(c("cDC_6H","T_PCD11_LCD11"))

#Circos 
LR <- createLRtable(fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(T_Cells_LCD11_vs_PCD11_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(T_Cells_LCD11_vs_PCD11_up_Receptors, cell_pairs[2], FC_thresh = 0), # REceptors
                   fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-Naive_",cell_pairs[2],"-PcDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "cDC_6H/Naive up regulated Ligands VS T_PcDC_LcDC/T_PcDC up regulated Receptors")
```




```{r}
########################MoDC_6H/Naive+cDC_6H VS T_PcDC_LMoDC/T_PcDC #######################

```
```{r}
#Preprocessing


RNAseqEXPMean <- merge(MoDC_Counts, T_Treatments_Counts_LMoDC, by = "row.names")
names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'
RNAseqEXPMean$MoDC_6H <- rowMeans(RNAseqEXPMean[,c("MoDC_6H_M1", "MoDC_6H_M2", "MoDC_6H_M3", "MoDC_6H_M4") ])
RNAseqEXPMean$T_PCD11_LMoDC <- rowMeans(RNAseqEXPMean[,c("T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("MoDC_6H_M1", "MoDC_6H_M2", "MoDC_6H_M3", "MoDC_6H_M4","T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4"))


#Circos 
cell_pairs <- c(c("MoDC_6H","T_PCD11_LMoDC"))

LR <- createLRtable(fromCol = ReceptorParser(MoDC6H_Intersected_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(T_Cells_LMoDC_vs_PcDC_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(T_Cells_LMoDC_vs_PcDC_up_Receptors, cell_pairs[2], FC_thresh = 0), # Receptors
                   fromCol = ReceptorParser(MoDC6H_Intersected_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-Naive+cDC_6H_",cell_pairs[2],"-PcDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "MoDC_6H/Naive+cDC_6H unique up regulated Ligands VS T_PcDC_LMoDC/T_PcDC up regulated Receptors")


```



```{r}
#SANITY CHECK:
#Ligands: "Tnfsf10", "Tnfsf4", "Calm1"
#Receptor: "Traf2"
#ALL Connected CHECKED (in LigandReceptorTable)

MoDC_cDC_Counts_Merge <- merge(MoDC_Counts,cDC_Counts,by = "row.names")
MoDC_cDC_Counts_Merge <- MoDC_cDC_Counts_Merge %>% tibble::column_to_rownames("Row.names")

#Ligands
Tnfsf10_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) %in% "Tnfsf10")
Tnfsf4_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Tnfsf4")
Calm1_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Calm1")


#Receptor
Traf2_LogFC_T_LMoDC_vs_PcDC <- subset(T_Treatments_Counts_LMoDC_PcDC, row.names(T_Treatments_Counts_LMoDC_PcDC) == "Traf2" )



data_Ligs_VS_Recps_box <-
  data.frame(
    NormalizedExpression = c(c(t(
      Tnfsf10_LogFC_MoDC6H_Unique
    )), c(t(
      Tnfsf4_LogFC_MoDC6H_Unique
    )), c(t(
      Calm1_LogFC_MoDC6H_Unique
    )), c(t(
      Traf2_LogFC_T_LMoDC_vs_PcDC
    ))),
    Gene = c(
      rep("Tnfsf10", 11),
      rep("Tnfsf4", 11),
      rep("Calm1", 11),
      rep("Traf2", 8)
    ),
    Experiment = c(rep(c(
      rep("MoDC_Naive", 3),rep("MoDC_6H", 4), rep("cDC_6H", 4)
    ), 3), rep("T_PimedcDC", 4),rep("T_PcDC_LMoDC", 4)),
    stringsAsFactors = F
  )

#c(rep("MoDC_6H/Naive+cDC_6H Ligands",3),"T_Cells_PcDC_LMoDC/PcDC Receptor"))


ggplot(data_Ligs_VS_Recps_box,
       aes(Gene,NormalizedExpression, fill = factor(Experiment, levels = c('MoDC_Naive', 'MoDC_6H', 'cDC_6H','T_PimedcDC','T_PcDC_LMoDC')))) + geom_boxplot(width = 0.5) +  theme(
    axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()
  ) +ggtitle("MoDC_6H/Naive+cDC_6H VS T_Cells_PcDC_LMoDC/PcDC") +
  theme(plot.title = element_text(size = 10)) + scale_fill_discrete(name = "Experiment") 
ggsave(".\\Circos_Code\\MoDC_6H-Naive+cDC_6H__VS__T_Cells_PcDC_LMoDC-PcDC__Traf2_Receptor.pdf",width=10,height=7)
```
```{r}
#SANITY CHECK:
#Ligands: "Adam17", "Calm1"
#Receptor: "Tnfrsf1b"
#ALL Connected CHECKED (in LigandReceptorTable)

MoDC_cDC_Counts_Merge <- merge(MoDC_Counts,cDC_Counts,by = "row.names")
MoDC_cDC_Counts_Merge <- MoDC_cDC_Counts_Merge %>% tibble::column_to_rownames("Row.names")

#Ligands
Adam17_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Adam17")
Calm1_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Calm1")


#Receptor
Tnfrsf1b_LogFC_T_LMoDC_vs_PcDC <- subset(T_Treatments_Counts_LMoDC_PcDC, row.names(T_Treatments_Counts_LMoDC_PcDC) == "Tnfrsf1b" )



data_Ligs_VS_Recps_box <-
  data.frame(
    NormalizedExpression = c(c(t(
      Adam17_LogFC_MoDC6H_Unique
    )), c(t(
      Calm1_LogFC_MoDC6H_Unique
    )), c(t(
      Tnfrsf1b_LogFC_T_LMoDC_vs_PcDC
    ))),
    Gene = c(rep("Adam17", 11), rep("Calm1", 11), rep("Tnfrsf1b", 8)),
    Experiment = factor(c(rep(c(
      rep("MoDC_Naive", 3),rep("MoDC_6H", 4), rep("cDC_6H", 4)
    ), 2),  rep("T_PimedcDC", 4),rep("T_PcDC_LMoDC", 4))),
    stringsAsFactors = F
  )

ggplot(data_Ligs_VS_Recps_box,
       aes(Gene,NormalizedExpression, fill = factor(Experiment, levels = c('MoDC_Naive', 'MoDC_6H', 'cDC_6H','T_PimedcDC','T_PcDC_LMoDC')))) + geom_boxplot(width = 0.5, aes(color = )) +  theme(
    axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()
  ) +ggtitle("MoDC_6H/Naive+cDC_6H VS T_Cells_PcDC_LMoDC/PcDC") +
  theme(plot.title = element_text(size = 10)) + scale_fill_discrete(name = "Experiment") 
ggsave(".\\Circos_Code\\MoDC_6H-Naive+cDC_6H__VS__T_Cells_PcDC_LMoDC-PcDC__Tnfrsf1b_Receptor.pdf",width=10,height=7)

```
```{r}
#SANITY CHECK:
#Ligands: "Pcdh7","Cxcl16", "Penk", "C3","App","Ccl5"
#Receptor: "Cxcr4"
#ALL Connected CHECKED (in LigandReceptorTable and LR)

MoDC_cDC_Counts_Merge <- merge(MoDC_Counts,cDC_Counts,by = "row.names")
MoDC_cDC_Counts_Merge <- MoDC_cDC_Counts_Merge %>% tibble::column_to_rownames("Row.names")

#Ligands
Pcdh7_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Pcdh7")
Cxcl16_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Cxcl16")
Penk_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Penk")
C3_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "C3")
App_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "App")
Ccl5_LogFC_MoDC6H_Unique <- subset(MoDC_cDC_Counts_Merge, row.names(MoDC_cDC_Counts_Merge) == "Ccl5")


#Receptor
Cxcr4_LogFC_T_LMoDC_vs_PcDC <- subset(T_Treatments_Counts_LMoDC_PcDC, row.names(T_Treatments_Counts_LMoDC_PcDC) == "Cxcr4" )



data_Ligs_VS_Recps_box <-
  data.frame(
    NormalizedExpression = c(c(t(
      Pcdh7_LogFC_MoDC6H_Unique
    )), c(t(
      Cxcl16_LogFC_MoDC6H_Unique
    )), c(t(
      Penk_LogFC_MoDC6H_Unique
    )), c(t(
      C3_LogFC_MoDC6H_Unique
    )),
     c(t(
      App_LogFC_MoDC6H_Unique
    )),
     c(t(
      Ccl5_LogFC_MoDC6H_Unique
    )),c(t(
      Cxcr4_LogFC_T_LMoDC_vs_PcDC
    ))),
    Gene = c(rep("Pcdh7", 11), rep("Cxcl16", 11),rep("Penk", 11),rep("C3", 11),rep("App", 11),rep("Ccl5", 11), rep("Cxcr4", 8)),
    Experiment = factor(c(rep(c(
      rep("MoDC_Naive", 3),rep("MoDC_6H", 4), rep("cDC_6H", 4)
    ), 6),  rep("T_PimedcDC", 4),rep("T_PcDC_LMoDC", 4))),
    stringsAsFactors = F
  )

#c(rep("MoDC_6H/Naive+cDC_6H Ligands",3),"T_Cells_PcDC_LMoDC/PcDC Receptor"))


ggplot(data_Ligs_VS_Recps_box,
       aes(factor(Gene, levels = c("Pcdh7","Cxcl16", "Penk", "C3","App","Ccl5","Cxcr4")),NormalizedExpression, fill = factor(Experiment, levels = c('MoDC_Naive', 'MoDC_6H', 'cDC_6H','T_PimedcDC','T_PcDC_LMoDC')))) + geom_boxplot(width = 0.5) +  theme(
    axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()
  ) +ggtitle("MoDC_6H/Naive+cDC_6H VS T_Cells_PcDC_LMoDC/PcDC") +
  theme(plot.title = element_text(size = 10)) + scale_fill_discrete(name = "Experiment") + scale_x_discrete(name = "Gene") 

ggsave(".\\Circos_Code\\MoDC_6H-Naive+cDC_6H__VS__T_Cells_PcDC_LMoDC-PcDC__Cxcr4_Receptor.pdf",width=10,height=7)

```




```{r}
########################cDC_6H/Naive VS T_PcDC_LMoDC/T_PcDC #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(cDC_Counts, T_Treatments_Counts_LMoDC, by = "row.names")

names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'

RNAseqEXPMean$cDC_6H <- rowMeans(RNAseqEXPMean[,c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4")])
RNAseqEXPMean$T_PCD11_LMoDC <- rowMeans(RNAseqEXPMean[,c("T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4","T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4"))

cell_pairs <- c(c("cDC_6H","T_PCD11_LMoDC"))

#Circos 
LR <- createLRtable(fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(T_Cells_LMoDC_vs_PcDC_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(T_Cells_LMoDC_vs_PcDC_up_Receptors, cell_pairs[2], FC_thresh = 0), # REceptors
                   fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-Naive_",cell_pairs[2],"-PcDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "cDC_6H/Naive up regulated Ligands VS T_PcDC_LMoDC/T_PcDC up regulated Receptors")
```

```{r}
########################cDC_6H/Naive VS T_PcDC_LMoDC/T_PcDC_LcDC #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(cDC_Counts, T_Treatments_Counts_LMoDC, by = "row.names")

names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'

RNAseqEXPMean$cDC_6H <- rowMeans(RNAseqEXPMean[,c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4")])
RNAseqEXPMean$T_PCD11_LMoDC <- rowMeans(RNAseqEXPMean[,c("T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4","T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4"))

cell_pairs <- c(c("cDC_6H","T_PCD11_LMoDC"))

#Circos 
LR <- createLRtable(fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(T_Cells_LMoDC_vs_LcDC_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(T_Cells_LMoDC_vs_LcDC_up_Receptors, cell_pairs[2], FC_thresh = 0), # REceptors
                   fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-Naive_",cell_pairs[2],"-PcDC_LcDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "cDC_6H/Naive up regulated Ligands VS T_PcDC_LMoDC/T_PcDC_LcDC up regulated Receptors")
```







```{r}
########################cDC_6H/Naive VS T_PcDC_LMoDC/T_PMoDC #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(cDC_Counts, T_Treatments_Counts_LMoDC, by = "row.names")

names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'

RNAseqEXPMean$cDC_6H <- rowMeans(RNAseqEXPMean[,c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4")])
RNAseqEXPMean$T_PCD11_LMoDC <- rowMeans(RNAseqEXPMean[,c("T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("CD11c_6H_M1", "CD11c_6H_M2", "CD11c_6H_M3", "CD11c_6H_M4","T_PCD11_LMoDC_1", "T_PCD11_LMoDC_2", "T_PCD11_LMoDC_3", "T_PCD11_LMoDC_4"))

cell_pairs <- c(c("cDC_6H","T_PCD11_LMoDC"))

#Circos 
LR <- createLRtable(fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(T_Cells_LMoDC_vs_PMoDC_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(T_Cells_LMoDC_vs_PMoDC_up_Receptors, cell_pairs[2], FC_thresh = 0), # REceptors
                   fromCol = ReceptorParser(cDC_6H_VS_cDC_Naive_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-Naive_",cell_pairs[2],"-PMoDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "cDC_6H/Naive up regulated Ligands VS T_PcDC_LMoDC/T_PMoDC up regulated Receptors")
```





```{r}
########################In vivo MoDC_Tumor/DLN VS T_Cells_Tumor/DLN #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(MoDC_In_Vivo_Counts_Tumor, T_Cells_In_Vivo_Counts_Tumor, by = "row.names")
names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'
RNAseqEXPMean$DC_Tumor <- rowMeans(RNAseqEXPMean[,c("DC_Tumor1","DC_Tumor2","DC_Tumor3") ])
RNAseqEXPMean$CD8_Tumor <- rowMeans(RNAseqEXPMean[,c("CD8_Tumor_1", "CD8_Tumor_2", "CD8_Tumor_3") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("DC_Tumor1","DC_Tumor2","DC_Tumor3","CD8_Tumor_1", "CD8_Tumor_2", "CD8_Tumor_3"))

#Circos 
cell_pairs <- c(c("DC_Tumor","CD8_Tumor"))

LR <- createLRtable(fromCol = ReceptorParser(MoDC_Tumor_VS_MoDC_DLN_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(In_vivo_T_cells_Tumor_vs_DLN_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(In_vivo_T_cells_Tumor_vs_DLN_up_Receptors, cell_pairs[2], FC_thresh = 0), # Receptors
                   fromCol = ReceptorParser(MoDC_Tumor_VS_MoDC_DLN_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-DLN_",cell_pairs[2],"-DLN_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "MoDC_Tumor/DLN up regulated Ligands VS T_cells_Tumor/DLN up regulated Receptors")


```




```{r}
########################In vivo MoDC_Tumor/DLN intersected with in vitro MoDC_6H/Naive+cDC_6H up ligands VS T_Cells_Tumor/DLN intersected with In vitro T_LMoDC/TcDC up receptors #######################

```
```{r}
#Preprocessing

RNAseqEXPMean <- merge(MoDC_In_Vivo_Counts_Tumor, T_Cells_In_Vivo_Counts_Tumor, by = "row.names")
names(RNAseqEXPMean)[names(RNAseqEXPMean) == 'Row.names'] <- 'gene_name'
RNAseqEXPMean$DC_Tumor <- rowMeans(RNAseqEXPMean[,c("DC_Tumor1","DC_Tumor2","DC_Tumor3") ])
RNAseqEXPMean$CD8_Tumor <- rowMeans(RNAseqEXPMean[,c("CD8_Tumor_1", "CD8_Tumor_2", "CD8_Tumor_3") ])
RNAseqEXPMean <- RNAseqEXPMean%>% dplyr::select(-c("DC_Tumor1","DC_Tumor2","DC_Tumor3","CD8_Tumor_1", "CD8_Tumor_2", "CD8_Tumor_3"))

#Circos 
cell_pairs <- c(c("DC_Tumor","CD8_Tumor"))

LR <- createLRtable(fromCol = ReceptorParser(MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands, cell_pairs[1], FC_thresh = 0), #use ReceptorParser instead
                      toCol   = ReceptorParser(In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors, cell_pairs[2], FC_thresh = 0),
                      num2compare = "All",
                      LigandReceptorTable = LigandReceptorTable,
                      EXP.Ligands = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[1]), # use RNAseqEXPParser instead
                      EXP.Receptors = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]),
                      enable_overlap = T)
  
  #write.table(LR, file = paste0(analysis_path,"Circos/",cell_line,"_LR.tsv"), quote = F, sep = "\t",
  #           row.names = F, col.names = T, qmethod = c("escape", "double"), fileEncoding = "")
  
  createCircosPlot(LR = LR,
                   toCol = ReceptorParser(In_vivo_T_cells_Tumor_vs_DLN_up_intersected_with_T_LMoDC_vs_PcDC_up_Receptors, cell_pairs[2], FC_thresh = 0), # Receptors
                   fromCol = ReceptorParser(MoDC_Tumor_VS_MoDC_DLN_up_intersected_MoDC_6H_unique_up_Ligands, cell_pairs[1], FC_thresh = 0),
                   threshold = 100,
                   LigandReceptorTable = LigandReceptorTable,
                   RNAseqEXPCol = RNAseqEXPParser(RNAseqEXPMean,cell_pairs[2]), #EXP.Receptors
                   Figure_name = paste0("C:\\Kfir_Thesis_Asaf_Madi\\Project_2 - BulkRNAseq\\Circos_Code\\",cell_pairs[1],"-DLN_X_MoDC_6H_unique_",cell_pairs[2],"-DLN_X_T_LMoDC-PcDC_Circos.pdf"), title = "Ligand-Receptor Interactions", subtitle = "MoDC_Tumor/DLN up regulated X MoDC_6H/Naive+cDC_6H up Ligands VS T_cells_Tumor/DLN X T_LMoDC/T_cDC up Receptors")


```



